[package]
name = "ratatui-macros"
version = "0.5.1"
edition = "2021"
authors = ["The Ratatui Developers"]
description = "Macros for Ratatui"
license = "MIT"                                              # or any other appropriate license
repository = "https://github.com/ratatui-org/ratatui-macros"
documentation = "https://docs.rs/ratatui-macros"
keywords = ["ratatui", "macros", "tui", "ui"]
categories = ["command-line-interface"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# requires alpha version of ratatui for the Into<Style> changes
ratatui = "0.28.1"

[dev-dependencies]
trybuild = { version = "1.0.99", features = ["diff"] }
cargo-husky = { version = "1.5.0", features = ["user-hooks"] }
